// Generated by https://quicktype.io

import { PaginationModel } from "../shared/models/pagination.model";

export interface Product {
  sku: number;
  name: string;
  categoryId: number;
  sellingPrice: number;
  categoryName?: string;
}

export interface PaginatedProduct extends PaginationModel {
  products: Product[];
}
