version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bco_gye_sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Dev!2025_Sql"
      MSSQL_PID: "Developer"
    volumes:
      - bco_guayaquil:/var/opt/mssql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - bco_guayaquil

volumes:
  bco_guayaquil:

networks:
  bco_guayaquil:
    driver: bridge
